[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ant_v0"]

[project]
name = "ant_v0"
version = "0.0.1"
dependencies = ["gymnasium", "pygame>=2.1.3", "pre-commit"]
